//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojaNawigacja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresy
    {
        public int IdTrasy { get; set; }
        public string MiejsceWyjazdu { get; set; }
        public string MiejsceDocelowe { get; set; }
        public Nullable<System.DateTime> DataDodania { get; set; }
    }
}
